# Site settings
title: "My Blog Title"
description: >
  My site description

url: ""
date_format: "MMM dd, yyyy"
paginate: 5

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    minute_read:    'minute read'