# Site settings
title: "Server-Side Swift"
description: Apple発のオープンソースプログラミング言語Swiftによるサーバーサイド開発の日本語情報サイト。サーバーサイドSwiftの入門やライブラリまとめ、実際に動いているサービスの紹介など。

url: "http://serversideswift.net/"
date_format: "MMM dd, yyyy"
paginate: 5

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    minute_read: 'minute read'

google_analytics: "UA-75934247-1"
disqus_shortname: "serversideswift-net"
ad: 1
