---
- hosts: all
  vars:
    swift_version: "swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a"
    apps:  
      - { name: "SSS", port: "9000", domain: "serversideswift.net" }
  tasks:
    - apt: name={{ item }} state=latest
      with_items:
        - nginx
        - git
        - clang
        - libicu-dev
        - make
        - supervisor

    - copy: src=.profile dest=/root/.profile owner=root group=root mode=0644
    - git: repo=https://github.com/kylef/swiftenv.git dest=/root/.swiftenv
    - command: "/root/.swiftenv/bin/swiftenv install {{ swift_version }}"
      ignore_errors: yes

    - git: repo=https://github.com/tnantoka/{{ item.domain }}.git dest=/var/www/{{ item.name }} update=yes
      with_items: "{{ apps }}"
    - shell: bash -lc "make release" chdir=/var/www/{{ item.name }}
      with_items: "{{ apps }}"

    - template: src=supervisor.j2 dest=/etc/supervisor/conf.d/{{ item.name }}.conf owner=root group=root mode=0644
      with_items: "{{ apps }}"
    - command: "supervisorctl reread"
    - command: "supervisorctl add {{ item.name }}"
      with_items: "{{ apps }}"
    - command: "supervisorctl reload"

    - template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ item.name }}.conf owner=root group=root mode=0644
      with_items: "{{ apps }}"
    - service: name=nginx state=restarted enabled=yes


